// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lweqgshhjljlwwtrsiwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3ZXFnc2hoamxqbHd3dHJzaXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDk1NzgsImV4cCI6MjA2OTA4NTU3OH0.s7nQjJb4gqhvYc2_47fFqGUtxiHzLTPPICmyCv10fLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});